In [37]:
import pandas as pd
import numpy as np

In [3]:
# Tek seferde datayı okuma
df = pd.read_csv("./data/houses_Madrid.csv")
df

,Unnamed: 0,id,title,subtitle,sq_mt_built,sq_mt_useful,n_rooms,n_bathrooms,n_floors,sq_mt_allotment,...,energy_certificate,has_parking,has_private_parking,has_public_parking,is_parking_included_in_price,parking_price,is_orientation_north,is_orientation_west,is_orientation_south,is_orientation_east
0,0,21742,"Piso en venta en calle de Godella, 64","San Cristóbal, Madrid",64.0,60.0,2,1.0,NaN,NaN,...,D,False,NaN,NaN,NaN,NaN,False,True,False,False
1,1,21741,Piso en venta en calle de la del Manojo de Rosas,"Los Ángeles, Madrid",70.0,NaN,3,1.0,NaN,NaN,...,en trámite,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,21740,"Piso en venta en calle del Talco, 68","San Andrés, Madrid",94.0,54.0,2,2.0,NaN,NaN,...,no indicado,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,21739,Piso en venta en calle Pedro Jiménez,"San Andrés, Madrid",64.0,NaN,2,1.0,NaN,NaN,...,en trámite,False,NaN,NaN,NaN,NaN,False,False,True,False
4,4,21738,Piso en venta en carretera de Villaverde a Val...,"Los Rosales, Madrid",108.0,90.0,2,2.0,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21737,21737,5,Ático en venta en Casco Histórico de Barajas,"Barajas, Madrid",78.0,NaN,2,2.0,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN
21738,21738,4,Piso en venta en Urb. Campo de las Naciones - ...,"Barajas, Madrid",96.0,83.0,2,2.0,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,False,True,True,True
21739,21739,3,Piso en venta en Campo de las Naciones-Corralejos,"Barajas, Madrid",175.0,NaN,4,2.0,NaN,NaN,...,E,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN
21740,21740,2,"Chalet adosado en venta en calle Burriana, 12","Campo de las Naciones-Corralejos, Madrid",289.0,NaN,4,3.0,3.0,304.0,...,en trámite,True,NaN,NaN,True,0.0,False,False,True,False
21741,21741,1,"Piso en venta en calle San Epifanio, 9","Imperial, Madrid",72.0,NaN,2,2.0,NaN,NaN,...,A,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN

In [18]:
# Chunk Data Okuma
dflist = pd.read_csv("./data/houses_Madrid.csv",chunksize=5000,index_col=False)
l = []
for df in dflist:
   l.append(df)

l[4]

,Unnamed: 0,id,title,subtitle,sq_mt_built,sq_mt_useful,n_rooms,n_bathrooms,n_floors,sq_mt_allotment,...,energy_certificate,has_parking,has_private_parking,has_public_parking,is_parking_included_in_price,parking_price,is_orientation_north,is_orientation_west,is_orientation_south,is_orientation_east
20000,20000,1742,"Piso en venta en Urb. Recoletos, Recoletos","Barrio de Salamanca, Madrid",390.0,NaN,5,4.0,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN
20001,20001,1741,Piso en venta en Goya,"Barrio de Salamanca, Madrid",469.0,NaN,6,4.0,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,False,True,False,False
20002,20002,1740,Piso en venta en Goya,"Barrio de Salamanca, Madrid",125.0,NaN,2,2.0,NaN,NaN,...,en trámite,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20003,20003,1739,"Piso en venta en Urb. Salamanca Prime, Castellana","Barrio de Salamanca, Madrid",412.0,NaN,5,5.0,NaN,NaN,...,no indicado,True,NaN,NaN,True,0.0,False,True,False,True
20004,20004,1738,Piso en venta en calle de Francisco Silvela,"Lista, Madrid",63.0,NaN,2,1.0,NaN,NaN,...,G,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21737,21737,5,Ático en venta en Casco Histórico de Barajas,"Barajas, Madrid",78.0,NaN,2,2.0,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN
21738,21738,4,Piso en venta en Urb. Campo de las Naciones - ...,"Barajas, Madrid",96.0,83.0,2,2.0,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,False,True,True,True
21739,21739,3,Piso en venta en Campo de las Naciones-Corralejos,"Barajas, Madrid",175.0,NaN,4,2.0,NaN,NaN,...,E,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN
21740,21740,2,"Chalet adosado en venta en calle Burriana, 12","Campo de las Naciones-Corralejos, Madrid",289.0,NaN,4,3.0,3.0,304.0,...,en trámite,True,NaN,NaN,True,0.0,False,False,True,False
21741,21741,1,"Piso en venta en calle San Epifanio, 9","Imperial, Madrid",72.0,NaN,2,2.0,NaN,NaN,...,A,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN

In [14]:
df = l[0]

In [20]:
cols =df.columns.to_list()

In [28]:
# Dropping Columns
df = df.drop('Unnamed: 0',axis=1)

In [29]:
# Data Types
df.dtypes

id                                int64
title                            object
subtitle                         object
sq_mt_built                     float64
sq_mt_useful                    float64
n_rooms                           int64
n_bathrooms                     float64
n_floors                        float64
sq_mt_allotment                 float64
latitude                        float64
longitude                       float64
raw_address                      object
is_exact_address_hidden            bool
street_name                      object
street_number                    object
portal                          float64
floor                            object
is_floor_under                   object
door                            float64
neighborhood_id                  object
operation                        object
rent_price                        int64
rent_price_by_area              float64
is_rent_price_known                bool
buy_price                         int64
buy_price_by_area                 int64
is_buy_price_known                 bool
house_type_id                    object
is_renewal_needed                  bool
is_new_development               object
built_year                      float64
has_central_heating              object
has_individual_heating           object
are_pets_allowed                float64
has_ac                           object
has_fitted_wardrobes             object
has_lift                         object
is_exterior                      object
has_garden                       object
has_pool                         object
has_terrace                      object
has_balcony                      object
has_storage_room                 object
is_furnished                    float64
is_kitchen_equipped             float64
is_accessible                    object
has_green_zones                  object
energy_certificate               object
has_parking                        bool
has_private_parking             float64
has_public_parking              float64
is_parking_included_in_price     object
parking_price                   float64
is_orientation_north             object
is_orientation_west              object
is_orientation_south             object
is_orientation_east              object
dtype: object

In [51]:
# Columndaki dataya erişmek
df['buy_price']

20000    2290000
20001    3200000
20002     695000
20003    2750000
20004     359000
          ...
21737     350000
21738     425000
21739     680000
21740     695000
21741     424000
Name: buy_price, Length: 1742, dtype: int64

In [52]:
df[df['buy_price'] < 680000 ]

,id,title,subtitle,sq_mt_built,sq_mt_useful,n_rooms,n_bathrooms,n_floors,sq_mt_allotment,latitude,...,energy_certificate,has_parking,has_private_parking,has_public_parking,is_parking_included_in_price,parking_price,is_orientation_north,is_orientation_west,is_orientation_south,is_orientation_east
20004,1738,Piso en venta en calle de Francisco Silvela,"Lista, Madrid",63.0,NaN,2,1.0,NaN,NaN,NaN,...,G,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20005,1737,Piso en venta en Guindalera,"Barrio de Salamanca, Madrid",33.0,NaN,2,1.0,NaN,NaN,NaN,...,en trámite,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20007,1735,Piso en venta en calle del Conde de Vilches,"Guindalera, Madrid",93.0,NaN,2,1.0,NaN,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,False,False,True,False
20008,1734,Ático en venta en Lista,"Barrio de Salamanca, Madrid",80.0,71.0,2,1.0,NaN,NaN,NaN,...,E,False,NaN,NaN,NaN,NaN,False,False,True,False
20010,1732,Piso en venta en calle de Ayala,"Goya, Madrid",102.0,NaN,3,2.0,NaN,NaN,NaN,...,en trámite,True,NaN,NaN,False,14550.0,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21735,7,Piso en venta en calle Bahía de Almería,"Campo de las Naciones-Corralejos, Madrid",88.0,NaN,2,2.0,NaN,NaN,NaN,...,no indicado,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN
21736,6,Piso en venta en calle Bahía de Alicante,"Campo de las Naciones-Corralejos, Madrid",99.0,NaN,2,2.0,NaN,NaN,NaN,...,no indicado,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN
21737,5,Ático en venta en Casco Histórico de Barajas,"Barajas, Madrid",78.0,NaN,2,2.0,NaN,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN
21738,4,Piso en venta en Urb. Campo de las Naciones - ...,"Barajas, Madrid",96.0,83.0,2,2.0,NaN,NaN,NaN,...,en trámite,True,NaN,NaN,True,0.0,False,True,True,True
21741,1,"Piso en venta en calle San Epifanio, 9","Imperial, Madrid",72.0,NaN,2,2.0,NaN,NaN,NaN,...,A,True,NaN,NaN,True,0.0,NaN,NaN,NaN,NaN

In [70]:
notnull =  df['latitude'].notnull().any()
notnull

False

In [81]:
## Null liste bulma
null_series = df['n_floors'].isnull()
null2 = null_series[null_series == False]
nullarr = np.array(null2.index)
nullarr.tolist()
for i in nullarr.tolist():
    print(df['n_floors'][i])

3.0
3.0
4.0
4.0
2.0
3.0
2.0
2.0
4.0
2.0
1.0
3.0
3.0
3.0
3.0
1.0
1.0
1.0
2.0
3.0
3.0
3.0
2.0
2.0
4.0
4.0
4.0
3.0
4.0
4.0
3.0
2.0
2.0
2.0
4.0
4.0
2.0
4.0
3.0
4.0
4.0
3.0
3.0
4.0
4.0
4.0
4.0
5.0
3.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
3.0
4.0
3.0
3.0
4.0
2.0
4.0
4.0
2.0
4.0
2.0
4.0
3.0
2.0
4.0
4.0
4.0
4.0
4.0
4.0
4.0
3.0
3.0
3.0
3.0
4.0
3.0
4.0
4.0
3.0
3.0
4.0
2.0
3.0